In [1]:
# colab에서 이 코드로 버전 바꿔가면서 사용할수 있는것

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
print (tf.__version__)

2.0.0


In [4]:
tf.executing_eagerly()

True

## Defining Tensors

In [5]:
m1 = [[1.0, 2.0], 
      [3.0, 4.0]]
m2 = np.array([[1.0, 2.0],
              [3.0, 4.0]], dtype=np.float32)
m3 = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

In [6]:
print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [7]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

In [8]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [9]:
print(t1)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


## Numpy Compatibility

In [10]:
ndarray = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)


print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())
ndarray

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Constants

In [11]:
hello = tf.constant("Hello World!")
print(hello)

tf.Tensor(b'Hello World!', shape=(), dtype=string)


In [12]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print(a.numpy())  # numpy를 붙이면 숫자만 나오고
print(b)    # 그냥 출력시키면 정보와 같이 나온다

1.5
tf.Tensor(2.5, shape=(), dtype=float32)


## Operations


In [13]:
a_plus_b = tf.add(a, b)
print(a_plus_b)

tf.Tensor(4.0, shape=(), dtype=float32)


In [14]:
a_mul_b = tf.multiply(a, b)
print(a_mul_b)

tf.Tensor(3.75, shape=(), dtype=float32)


## Variables

In [15]:
weight = tf.Variable(tf.random_normal_initializer(stddev=0.1)([5, 2]))
print(weight)

# placeholder에 따로 넣지 않고, initializer도 따로 안해줘도 됨

<tf.Variable 'Variable:0' shape=(5, 2) dtype=float32, numpy=
array([[ 0.00062101, -0.1820244 ],
       [-0.10126316,  0.08947258],
       [-0.12483281, -0.03198363],
       [ 0.08153451, -0.08219332],
       [-0.08862903, -0.09852479]], dtype=float32)>


## Create a Dataset

In [16]:
a = np.arange(10)
print(a)
ds_tensors = tf.data.Dataset.from_tensor_slices(a)

[0 1 2 3 4 5 6 7 8 9]


## Apply Transformations

In [17]:
ds_tensors = ds_tensors.map(tf.square).shuffle(20).batch(2)

# (square)의 자리에는 인자의 수를 맞추어 넣어야 한다.
# 예를 들어 a안에 인자는 10개. 그 열개를 맞춰야 한다.
# preprocessing 할때 많이 사용된다. 

## Iterate

In [19]:
print('Elements of ds_tensors:')
for _ in range(3):  # 밖은 epoch  (전체데이터 돌아가기)
  for x in ds_tensors.take(2):   # 안은 batch   # take : 2번만 가져와라
    print(x)

Elements of ds_tensors:
tf.Tensor([4 0], shape=(2,), dtype=int32)
tf.Tensor([49 25], shape=(2,), dtype=int32)
tf.Tensor([9 1], shape=(2,), dtype=int32)
tf.Tensor([64 49], shape=(2,), dtype=int32)
tf.Tensor([25  0], shape=(2,), dtype=int32)
tf.Tensor([4 9], shape=(2,), dtype=int32)
