# 2020.01.06

# numpy

In [2]:
# flask
# import flask     # 웹서버를 연결시켜주는 기능. 5000번 포트로 서비스


# https://wikidocs.net/32829   <- 판다스, 넘파이 설명

In [2]:
import matplotlib       # 시각화 패키지
import numpy as np      # 별칭, class로 구성
print(np.__version__)    # 상위 오브젝트가 가진 속성
def pprint(arr):         # ndarray : numpy의 기본 데이터 배열
    print("type:{}".format(type(arr)))
    print("shape:{}, dimension:{}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)
    # 숫자의 디폴트는 int32
arr = [1.0,2.0,3.0]  #리스트
a = np.array([1,2,3]) # ndarray 생성함수 : 매개변수 : 리스트 
pprint(a)

1.16.5
type:<class 'numpy.ndarray'>
shape:(3,), dimension:1, dtype:int32
Array's Data:
 [1 2 3]


In [5]:
# 인스턴스 상태
a = np.array([0,1,2,3,4,5,6,7,8,9])  # ndarray
print(id(a))   # python core 주소값 확인
print(a.size)   # 데이터 개수 
print(a.astype(np.float32))    # 데이터 타입변경. numpy는 행중심. 동질적
print(a.dtype.itemsize*a.size)   # 전체 메모리 사이즈 (바이트)
# iterator for in range => list
a = np.arange(1000)   # => ndarray  
a

2816926270208
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
40


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [68]:
# ndarray 초기화 함수들
print(np.zeros((3,4)))  #0 // 튜플로 3,4 를 하나로 묶은거라서 괄호가 1개, 함수용 괄호1개 , 프린트 괄호1개 => 총 3개 괄호
print(np.ones((2,3,4), dtype = np.int16)  # int16 형으로 저장되어 지고 3차원 면, 행, 열 
print(np.full(((2,2),7)))
print(np.eye(4))  # 대각행렬 identity   행렬연산에서 항등원 +,*
print(np.empty((4,2)))  # 쓰레기값


# 2차원이면 꺽새 2개, 3차원이면 3개

SyntaxError: invalid syntax (<ipython-input-68-62bedb98584d>, line 4)

In [6]:
a = np.arange(0,100,10)  # ndarray
indices = [1,5,-1]    # 리스트 
print(indices)
b = a[indices]   # 리스트를 첨자로 사용
print(a)
print(b)

[1, 5, -1]
[ 0 10 20 30 40 50 60 70 80 90]
[10 50 90]


In [12]:
a = np.arange(11,36)  # 1차원  /  개수가 맞춰져야한다. (35 이면 안됨)
print(a)
a.shape = (5,5)   # 정상모양을 갖춘 개수 R 
print(a)
print(type(a))
print(a.dtype)
print(a.size)
print(a.shape)  # 차수(5,5)
print(a.ndim)     # 2차원
print(a.nbytes)  #100바이트 = 25 * 4
print(a.strides)  # (20,4)   # 다음열의 데이터는 몇바이트를 건너 뛰어야하는가
                 # 다음 행은 몇바이트를 건너뒤어야 하는가 

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
<class 'numpy.ndarray'>
int32
25
(5, 5)
2
100
(20, 4)


In [13]:
arr = np.arange(10)   # 0부터 시작해서 9까지 10개
print(type(arr))
print(arr)
print(arr[5])
print(arr[5:8])  # 마지막 불포함
arr[5:8] = 12   # 데이터 update
print(arr[1:6])   # 마지막 답 12 로 change

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 1  2  3  4 12]


In [16]:
# numpy 첨자생략불가 [,4]
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0])  # 행우선 : 행
print(arr2d[0][2])
print(arr2d[0,2])
print(arr2d[:2])  # 0,1 행
print(arr2d[:2,1:]) # 끝까지
print(arr2d[:,1:])   # 모든행.  꼭 전체행을 나태내야 한다. (1 앞에 :)
print(arr2d[1,:2])
print(arr2d[2,:1])
arr2d[:2,:1] = 0
arr2d[:2,:1] = 0
print(arr2d)

[1 2 3]
3
3
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]
 [8 9]]
[4 5]
[7]
[[0 2 3]
 [0 5 6]
 [7 8 9]]


In [17]:
# 실제 저장은 일렬로 , 사람이 데이터를 다루는 것은 입체로  . 때문에 strides 를 사용하는 것 
# 실제로 저장은 일렬로 쭉 이어서 저장이 되는것이다. (사람이 보는것은 입체로 보는것)
# 행렬연산에서 앞의 행렬열수와 뒤의 행렬의 행수를 일치 시켜야 행렬곱이 가능
# 행렬곱에서 행렬 앞뒤로 바꾸면 안됨

print("스트라이드의 값", np.ones((3,4,5),dtype = np.float64).strides)   # 3면 4행 5열

# 8이 나오는 이유 : 단일 데이터가 float64라서 : 8바이트
# 한행을 지나가려면 5개 열을 지나야 해서 40
# 5열을 지나가야 하고 4행을 지아가야 해서 160

스트라이드의 값 (160, 40, 8)


In [27]:
# 문제
arr3d = np.array([  [[1,2,3],[4,5,6]],   [[7,8,9],[10,11,12]]    ])    # 2면 2행 3열 (2,2,3)
print("첫면은 ",arr3d[0])  #  0번 면
print("첫차원 첫행은 = ", arr3d[0][0])
print("첫요소는 = " , arr3d[0][0][0])
print("8을 출력", arr3d[1][0][1])
print("12출력", arr3d[1][1][2])  # [면][행][열]

첫면은  [[1 2 3]
 [4 5 6]]
첫차원 첫행은 =  [1 2 3]
첫요소는 =  1
8을 출력 8
12출력 12


In [28]:
# 백업이 안됨
# old_values=arr3d   # 대입 : 주소를 복사 // 같은 위치를 가르키기 때문에 백업이 안됨 (이전값으로 복구 안됨)

# 백업이 됨 - copy()
old_values=arr3d.copy()   # copy()를 사용하면 됨
arr3d[0]=42
print("값의 변경후")
print(arr3d)
print("이전 값으로 복구")
arr3d = old_values
print(arr3d)

값의 변경후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [26]:
Z= np.arange(36)
print(Z)
Z = Z.reshape((6,6))
reshape2 = Z.reshape((2,3,6))
print(reshape2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [9]:
arr=np.arange(32).reshape((8,4))
print(arr)
print(arr[[1,5,7,2]])  # 행 중심
print(arr[[-1,-5,-7,-2]]) # 꺼꾸로 인덱싱
print(arr[[1,5,7,2],[0,3,1,2]]) # 1행0열, 5행3열...이렇게 짝지어서 출력
# fancy 인덱싱 - 먼저 행을 지정해줘야한다
print(arr[[1,2,5,7]][:,[0,1,2,3]])  # :앞에서 나온행 전체(1,2,5,7)과  열을 짝지어사??????
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]
[ 4 23 29 10]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [27]:
# 0 - 55까지 6X6으로 array 만들기 (이중 for문)
arr=[]
for i in range(6):
    ad=[]
    for j in range(6):
        ad.append(i*10 + j)
    arr.append(ad)
print(arr)
arr=np.array(arr)

# 색입히기 - 몰라
print("주황색", arr[[0,1,2,3,4],[1,2,3,4,5]])
print("빨강색", arr[[0,2,5],2])
print("하늘색", arr[3:6][:,[0,2,5]])

print("두번째 색입히기")
#rint("빨간색", arr[0][2:5][1:][2])

print("빨간색", arr[:,2])
print("주황색",arr[0,[3,4]])
print("녹색", arr[[2,4]][:,[0,2,4]])
print("green", arr[4:][:,[4,5]])


[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]
주황색 [ 1 12 23 34 45]
빨강색 [ 2 22 52]
하늘색 [[30 32 35]
 [40 42 45]
 [50 52 55]]
두번째 색입히기
빨간색 [ 2 12 22 32 42 52]
주황색 [3 4]
녹색 [[20 22 24]
 [40 42 44]]
green [[44 45]
 [54 55]]


In [31]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])   #4X3
# 이렇게 나올것(4X3)
#[1,2,3]
#[4,5,6]
#[7,8,9]
# [10,11,12]

v = np.array([1,0,1])
print("타일출력")
vv = np.tile(v,(4,1))
print(vv)  # 4X3
y = x+vv  # 4X3 배열연산 => 요소별 연산
print(y)
# 배열연산 : 양족 차원이 일치해야한다. (곱하기 말고 덧셈,뺄셈?)
x+v   # x는 4X3이고 v 는 1X3 이라서 곱하기 연산이 된다. => broadcasting   (열!! 매칭)
x+3  # 상수는 모든 데이터에 일치해서 각 요소에 더해진다. 

print(x+v)
print(x+3)

타일출력
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [38]:
x = np.arange(6).reshape((3,2))  #3X2행렬
print(x)

# 거듭제곱(행열곱): @
#x@x   => 에러 : 앞의 행렬 열수와 뒤의 행렬의 행수가 일치하지 않아서 에러
# (3X2) (3X2) 하서 맞지 않다
# 전치행렬(T) 
#     -> 뒤에것을 (2X3)으로 바궈주기
x@x.T   # 3X3
print(np.transpose(x))

[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]


In [43]:
arr=np.arange(24).reshape((2,3,4))   #원래  0,1,2
print(arr)
print("면행바꾸기")
print(arr.transpose(1,0,2))   # 면과 행을 바꿔라 (앞에 1,0을 바꿔라) - 3면2행4열
print("전체다 바꾸기")
print(arr.transpose(0,2,1))  # 2면 4행 3열

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
면행바꾸기
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
전체다 바꾸기
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


# 다시보기 

In [47]:
# Boolean indexing (True/False)

names = np.array(['Seoul','Daejun','chungju','seoul','chungju', 'Daejun', 'Daejun'])   # 문자열배열 - 대소문자 구분
data = np.random.randn(7,4)  # 7X4 숫자열
print("names==Seoul") 
print(names=='Seoul')   # 1,0,0,0,0,0

print(data[names=='Seoul'])  # 첫번재 있는 0번행만 출력 'Seoul' => 인덱싱

print(data[names=='Seoul',2:])  # 첫행에서 2번재에서 끝

print(data[names=='Seoul',3])

print(names!='Seoul')    # 0,1,1,1,1,1  (0빼고 다 출력)

print(~(names=='Seoul'))  #  ~는 괄호안에것의 부정

mask = (names == 'Seoul') | (names=='chungju') 
print(mask)
print(data[mask])

names==Seoul
[ True False False False False False False]
[[ 9.36366388e-01 -1.31702386e-01 -1.04508885e+00 -2.15360861e-04]]
[[-1.04508885e+00 -2.15360861e-04]]
[-0.00021536]
[False  True  True  True  True  True  True]
[False  True  True  True  True  True  True]
[ True False  True False  True False False]
[[ 9.36366388e-01 -1.31702386e-01 -1.04508885e+00 -2.15360861e-04]
 [-9.65635636e-01 -1.10562780e+00  1.97958701e+00 -1.28416160e+00]
 [-5.64658740e-01 -1.75568359e-01 -9.25901328e-01 -4.81611277e-01]]


In [67]:
print(data)

[[ 9.36366388e-01 -1.31702386e-01 -1.04508885e+00 -2.15360861e-04]
 [ 1.11098463e+00 -5.31753285e-01  5.43479708e-01 -1.27570314e+00]
 [-9.65635636e-01 -1.10562780e+00  1.97958701e+00 -1.28416160e+00]
 [ 2.07650651e-01  2.66570843e-01  1.63814888e+00  5.18045136e-01]
 [-5.64658740e-01 -1.75568359e-01 -9.25901328e-01 -4.81611277e-01]
 [ 2.36961431e-02  8.73678426e-02  1.57813190e+00 -2.15017904e+00]
 [-1.51020331e+00 -1.07000294e+00  7.82170178e-01 -1.25244455e+00]]


# 다시보기

In [55]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, False, True])
print(zip(xarr, yarr, cond))   # zip : 요소별로 데이터 묶음, zip은 고유포멧이라서 안보이고
print(list(zip(xarr, yarr, cond)))                         # 그래서 list해서 보내줘야한다
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]   # 3항 연산자
print("result = ",result)

result = np.where(cond, xarr, yarr)
print(result)


[(1.1, 2.1, True), (1.2, 2.2, False), (1.3, 2.3, True), (1.4, 2.4, False), (1.5, 2.5, True)]
result =  [1.1, 2.2, 1.3, 2.4, 1.5]
[1.1 2.2 1.3 2.4 1.5]


In [70]:
# random 난수 정규분포에서 출력 16개 출력
arr = np.random.randn(4,4)
print(arr)
print(np.where(arr > 0, 2, -2))

[[ 0.00677118 -0.43596603  0.09885356  1.89075939]
 [ 0.55189904 -0.82486045  1.06995468  0.5004081 ]
 [-1.66591334  0.0386459  -0.75177684  0.54793085]
 [-0.19673181 -0.16373634 -0.142094    0.21065109]]
[[ 2 -2  2  2]
 [ 2 -2  2  2]
 [-2  2 -2  2]
 [-2 -2 -2  2]]


# 다시보기 

In [ ]:
# 문제) 
# 다음 데이터를 이용하여 두개 다 참일 때는 0, cond1이 참일때는 1, cond2 가 참일때는 2, 그 외일 때는 3으로 처리하여 출력하도록 하시오
# 0,1,2,3
# 조건 4
# where 3

In [71]:
result = []
cond1 = np.array([1,0,1,1,0,0,1], dtype = bool)
cond2 = np.array([0,1,1,1,0,1,1], dtype = bool)

for i in range(len(cond1)):
    if (cond1[i] and cond2[i]):
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)
print("조건문", result)
result = np.where(cond1 & cond2,0, np.where (cond1,1, np.where(cond2,2,3)))


print("3항연산자", result)
result = 1*(cond1 & ~cond2) + 2*(cond2 & ~cond1) + 3* ~(cond1 | cond2)  # 마지막 3 은 거짓을 부정한 것이니까 참.
print("수식을 이용한", result)

조건문 [1, 2, 0, 0, 3, 2, 0]
3항연산자 [1 2 0 0 3 2 0]
수식을 이용한 [1 2 0 0 3 2 0]


# zeros_like

In [72]:
x = np.arange(1,10001)
y = np.arange(10001,20001)

z = np.zeros_like(x)   # zeros_like : 다른 행렬과 같은 사이즈로 초기화  / ..?
for i in range(10000):
    z[i] = x[i] + y[i]

# np.exp : 지수함수e 

In [74]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
print(np.all(a == b))  # all : 전체가 참일때 참
print(np.any(a == b))  # any : 하나라도 참이면 참
print(np.exp(a))    # 지수함수 (자연대수 : 2.718)

# y = a^x
#        에서 y 값을 모를때 지수함수 e

False
True
[ 2.71828183  7.3890561  20.08553692 54.59815003]


# 선형대수 : 선형으로 해결 => 비선형도 잘게 나누면 선형
#  - 원점에서 나가는 모든 선. 그 선들의 각은 내적으로 구한다

#  - 차원 추가 / 축소 
#  - 사이각 - 내적으로 구하기 ( cos 사이각. 유사도 )
#  - 외적 : vector - 방향값 
#  - 내적 : scalar
# norm 

# https://eda-ai-lab.tistory.com/383   내적/외적 참고


# degree는 사람이 이해하는 각도 / radian은 구의 길이를 각도로. (calc할때)

# 분해

# 행렬 분해 : 역행렬을 구하기 위해서 
# 정방행렬 : 행수와 열수가 같은 행렬 

# 상관분석 - 대칭행렬 & 정방행렬
 1. 상관계수 : -1 ~ 1 사이의 값으로 공분산을 평준화 한 값
 2. 공분산( 음의 값 존재 ): 대칭을 중심으로 
 
 # 고유벡터 : 새롭게 만들어진 축(직교하는 축) 을 가지고 원래 있던 축과 비교.
 
 # SVD : 특징 추출 - 희소행렬
 # 행렬연산 => 특징추출!!

# ndarray

# ndarray
 
CPU에서 감당이 안되는걸 GPU로 행렬형태로 던져서 속도 빠르게. / 한거번에 대량을 계산한다(천단위)
행열이 하는 역할은 벡터를 변환해서 다른 곳으로 이동시킨다

벡터 * 매트릭스 : 공간을 변환하는것
매트릭스 * 매트릭스 : 변환의 합

MRS : mpove rotate scale

특징추출 : 많은 변수들 사이에서 사잇각을 구해서 (내적) 같은 특징을 합쳐서 소수로 분류한다 ( 차원축소 라고도 함)
매트릭스는 분류 & 예측........?

# vector
대각선 - 크기 (scaling)

unequal scaling - ?

rotate - 역방향(-), 정방향(+)

# vector & matrix ( 공간)


# 행렬의 종류

In [ ]:
# 행렬의 종류
- 정방행렬 : 정사각형(행과 열수가 같은 행렬)
- 대칭행렬 : 우상단과 좌하단이 같은 것
           : 모든 상관분석을 하기 위해 행과 열의 같은 변수를 준다. 
- 대각행렬 : scale을 변화시키는 요소 (대각행렬이 전부 1이면 다른거랑곱했을때 자신이 나옴)
- 단위행렬(identity) : 행렬곱의 항등원, 행렬과 역행렬을 곱하면 단위행렬
- 역행렬 : 행렬의 나눗셈을 구해서 곱해지는 행렬( 정방행렬만 가능 )
- 특이행렬 : 역행렬이 없는 행렬
- 직교행렬 : 축의 정직교
           : 각 축간의 내적이 0 인 행렬
- 정방행렬이면서 대칭행렬 : 공분산행렬, 상관계수 행렬, 거리행렬
- 공분산 : 두 수간의 관계 ((한수 - 평균) * (다른수 - 평균)) / (n-1)
- 상관계수(표준화 -1 ~1) : 공분산 / 표준편차의 곱

In [76]:
import numpy as np
F1 = np.array([[1,2],[3,4]])   # 2X2
F2 = np.array([[2,2],[2,2]])    # 2X2
# 1,2   2,2
# 3,4   2,2
print(F1)
print(F2)
print(F1 + F2)   # 요소끼리 +
print(F1 * F2)   # 요소끼리 *
print(F1 @ F2) 

# 행렬의 곱도 내적
 
# 1,2   2,2   =>  6 ,6         두  벡터의 사이각을 구해 차원확장
# 3,4   2,2   => 14,14


# 딥러닝 -> 한번에 여러개의 변수에서 2개로 축소시키는게 아니라 조금씩 차원 축소해서 값을 얻어간다
3

[[1 2]
 [3 4]]
[[2 2]
 [2 2]]
[[3 4]
 [5 6]]
[[2 4]
 [6 8]]
[[ 6  6]
 [14 14]]


# 다시보기

In [86]:
# 방정식의 해
#  2x1 + x2 -2x3 = -3
#  3x1 +    + x3  = 5
# x1 + x2  -x3  = -2

In [156]:
# 방정식 해 (x구하기)
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
print(A)
b = np.transpose(np.array([[-3,5,-2]]))  #열로 전치
print(b)
x = np.linalg.solve(A,b)  #A 의 역행렬을 구해서 b와 곱해줌
print(x)

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
[[-3]
 [ 5]
 [-2]]
[[ 1.]
 [-1.]
 [ 2.]]


In [157]:
np.dot(np.linalg.inv(A),b)   # 행렬곱

array([[ 1.],
       [-1.],
       [ 2.]])

In [158]:
np.linalg.inv(A)@b   # 왜 역행렬을 구해야하는가 ? 행렬은 나눗셈이 없어서 역행렬 곱해야 한다 

array([[ 1.],
       [-1.],
       [ 2.]])

In [1]:
# 검산

2*(1) + 1*(-1) -2*(2)

-3

In [88]:
a = np.array([0,1,0])   # y
b = np.array([1,0,0])   # x
res = np.dot(a,b)  # 내적 사이각 = 직각
print(res)

0


In [90]:
print(np.linalg.norm(a)) # 벡터의 크기
print(np.linalg.norm(b))
print(np.linalg.norm(a)* np.linalg.norm(b))
rad = res / (np.linalg.norm(a))*(np.linalg.norm(b))   # cos(theta)
print("cos theta" , rad)
print(np.arccos(rad))# theta 값을 구함
print(np.degrees(np.arccos(rad)))  # 사람이 알아보는 각도로 표현

1.0
1.0
1.0
cos theta 0.0
1.5707963267948966
90.0


In [ ]:
# 정방향행렬 * 역행렬 = identity( 단일행렬 )

In [91]:
x = np.array([[1,2], [3,4]])
y = np.linalg.inv(x)
print(x)
print(y)
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [ ]:
# 다음 방정식의 해를 구하고 검산하시오

x + y + z = 6
   2y + 5z = -4
2x + 5y -z = 27

In [3]:
c = np.array([[1, 1 ,1],[0, 2, 5],[2, 5, -1]])
print(c)
d = np.transpose(np.array([[6,-4, 27]]))
x = np.linalg.solve(c,d)
print(x)

[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
[[ 5.]
 [ 3.]
 [-2.]]


In [142]:
np.dot(np.linalg.inv(a),b)  
np.linalg.inv(a)@b

array([[14.76190476],
       [ 1.57142857],
       [-4.38095238]])

In [4]:
2*(3) + 5*(- 2)

-4

# numpy 함수
- array는 , 출력
- arange는 ,가 없고 (숫자 나열) -> 하고 reshape을 해야 행열. 